/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-22 15:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.Spmem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import spmem.VO.spmemVO;

public final class AtmosUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("spmem.VO.spmemVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/shorthandcss@1.1.1/dist/shorthand.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Muli:200,300,400,500,600,700,800,900&display=swap\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("  <script>\n");
      out.write("  $( function() {\n");
      out.write("    $( \"#tabs\" ).tabs();\n");
      out.write("  } );\n");
      out.write("  function regAtmos1(){\n");
      out.write("\t\tcent1option = document.getElementById(\"cent1option\");\n");
      out.write("\t\tcent2option = document.getElementById(\"cent2option\");\n");
      out.write("\t\tcent3option = document.getElementById(\"cent3option\");\n");
      out.write("\t\tcent4option = document.getElementById(\"cent4option\");\n");
      out.write("\t\tcent5option = document.getElementById(\"cent5option\");\n");
      out.write("\t\tcent6option = document.getElementById(\"cent6option\");\n");
      out.write("\t\tcent1 = document.getElementById(\"cent1\")\n");
      out.write("\t\tcent2 = document.getElementById(\"cent2\")\n");
      out.write("\t\tcent3 = document.getElementById(\"cent3\")\n");
      out.write("\t\tcent4 = document.getElementById(\"cent4\")\n");
      out.write("\t\tcent5 = document.getElementById(\"cent5\")\n");
      out.write("\t\tcent6 = document.getElementById(\"cent6\")\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"/SpinUrOwn/regAtmos.ma\",\n");
      out.write("\t\t\ttype:\"POST\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tcent1option : cent1option.value,\n");
      out.write("\t\t\t\tcent2option : cent2option.value,\n");
      out.write("\t\t\t\tcent3option : cent3option.value,\n");
      out.write("\t\t\t\tcent4option : cent4option.value,\n");
      out.write("\t\t\t\tcent5option : cent5option.value,\n");
      out.write("\t\t\t\tcent6option : cent6option.value,\n");
      out.write("\t\t\t\tcent1 : cent1.value,\n");
      out.write("\t\t\t\tcent2 : cent2.value,\n");
      out.write("\t\t\t\tcent3 : cent3.value,\n");
      out.write("\t\t\t\tcent4 : cent4.value,\n");
      out.write("\t\t\t\tcent5 : cent5.value,\n");
      out.write("\t\t\t\tcent6 : cent6.value\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\talert(\"AtmostUpdate1 done!\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});//ajax end\n");
      out.write("\t}\n");
      out.write("  function regAtmos2(){\n");
      out.write("\t\tcent1option = document.getElementById(\"2cent1option\");\n");
      out.write("\t\tcent2option = document.getElementById(\"2cent2option\");\n");
      out.write("\t\tcent3option = document.getElementById(\"2cent3option\");\n");
      out.write("\t\tcent4option = document.getElementById(\"2cent4option\");\n");
      out.write("\t\tcent5option = document.getElementById(\"2cent5option\");\n");
      out.write("\t\tcent6option = document.getElementById(\"2cent6option\");\n");
      out.write("\t\tcent1 = document.getElementById(\"2cent1\")\n");
      out.write("\t\tcent2 = document.getElementById(\"2cent2\")\n");
      out.write("\t\tcent3 = document.getElementById(\"2cent3\")\n");
      out.write("\t\tcent4 = document.getElementById(\"2cent4\")\n");
      out.write("\t\tcent5 = document.getElementById(\"2cent5\")\n");
      out.write("\t\tcent6 = document.getElementById(\"2cent6\")\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"/SpinUrOwn/regAtmos.ma\",\n");
      out.write("\t\t\ttype:\"POST\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tcent1option : cent1option.value,\n");
      out.write("\t\t\t\tcent2option : cent2option.value,\n");
      out.write("\t\t\t\tcent3option : cent3option.value,\n");
      out.write("\t\t\t\tcent4option : cent4option.value,\n");
      out.write("\t\t\t\tcent5option : cent5option.value,\n");
      out.write("\t\t\t\tcent6option : cent6option.value,\n");
      out.write("\t\t\t\tcent1 : cent1.value,\n");
      out.write("\t\t\t\tcent2 : cent2.value,\n");
      out.write("\t\t\t\tcent3 : cent3.value,\n");
      out.write("\t\t\t\tcent4 : cent4.value,\n");
      out.write("\t\t\t\tcent5 : cent5.value,\n");
      out.write("\t\t\t\tcent6 : cent6.value\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\talert(\"AtmostUpdate2 done!\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});//ajax end\n");
      out.write("\t}\n");
      out.write("  function regAtmos3(){\n");
      out.write("\t\tcent1option = document.getElementById(\"3cent1option\");\n");
      out.write("\t\tcent2option = document.getElementById(\"3cent2option\");\n");
      out.write("\t\tcent3option = document.getElementById(\"3cent3option\");\n");
      out.write("\t\tcent4option = document.getElementById(\"3cent4option\");\n");
      out.write("\t\tcent5option = document.getElementById(\"3cent5option\");\n");
      out.write("\t\tcent6option = document.getElementById(\"3cent6option\");\n");
      out.write("\t\tcent1 = document.getElementById(\"3cent1\")\n");
      out.write("\t\tcent2 = document.getElementById(\"3cent2\")\n");
      out.write("\t\tcent3 = document.getElementById(\"3cent3\")\n");
      out.write("\t\tcent4 = document.getElementById(\"3cent4\")\n");
      out.write("\t\tcent5 = document.getElementById(\"3cent5\")\n");
      out.write("\t\tcent6 = document.getElementById(\"3cent6\")\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"/SpinUrOwn/regAtmos.ma\",\n");
      out.write("\t\t\ttype:\"POST\",\n");
      out.write("\t\t\tdata: {\n");
      out.write("\t\t\t\tcent1option : cent1option.value,\n");
      out.write("\t\t\t\tcent2option : cent2option.value,\n");
      out.write("\t\t\t\tcent3option : cent3option.value,\n");
      out.write("\t\t\t\tcent4option : cent4option.value,\n");
      out.write("\t\t\t\tcent5option : cent5option.value,\n");
      out.write("\t\t\t\tcent6option : cent6option.value,\n");
      out.write("\t\t\t\tcent1 : cent1.value,\n");
      out.write("\t\t\t\tcent2 : cent2.value,\n");
      out.write("\t\t\t\tcent3 : cent3.value,\n");
      out.write("\t\t\t\tcent4 : cent4.value,\n");
      out.write("\t\t\t\tcent5 : cent5.value,\n");
      out.write("\t\t\t\tcent6 : cent6.value\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\talert(\"AtmostUpdate3 done!\")\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});//ajax end\n");
      out.write("\t}\n");
      out.write("  </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<hr/>\n");
spmemVO vo = (spmemVO)session.getAttribute("vo");
String Atmos = vo.getPreferAtmos().toString();
      out.write("\n");
      out.write("<div id=\"tabs\">\n");
      out.write("  <ul>\n");
      out.write("    <li><a href=\"#tabs-1\">Atmosphere1</a></li>\n");
      out.write("    <li><a href=\"#tabs-2\">Atmosphere2</a></li>\n");
      out.write("    <li><a href=\"#tabs-3\">Atmosphere3</a></li>\n");
      out.write("  </ul>\n");
      out.write("  <div id=\"tabs-1\">\n");
      out.write("<form method=\"post\" class=\"white fs-m3 fw-200\"\n");
      out.write(" action=\"/SpinUrOwn/regAtmos.ma\">\n");
if(Atmos=="0"
	||Atmos.split(" ").length!=5){ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz show your prefer Atmos!<br/>\n");
}else{ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz modify your prefer Atmos!<br/>\n");
      out.write("\t\t");
} 
      out.write("\n");
      out.write("\t\t<select name=\"cent1option\" id=\"cent1option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">gorgeous</option>\n");
      out.write("\t\t\t<option value=\"2\">amazing</option>\n");
      out.write("\t\t\t<option value=\"3\">nice</option>\n");
      out.write("\t\t\t<option value=\"4\">beautiful</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent1\" id=\"cent1\"> <br/>\n");
      out.write("\t\t<select name=\"cent2option\"id=\"cent2option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">honest</option>\n");
      out.write("\t\t\t<option value=\"2\">powerful</option>\n");
      out.write("\t\t\t<option value=\"3\">different</option>\n");
      out.write("\t\t\t<option value=\"4\">incredible</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent2\" id=\"cent2\"> <br/>\n");
      out.write("\t\t<select name=\"cent3option\" id=\"cent3option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">flawless</option>\n");
      out.write("\t\t\t<option value=\"2\">raw</option>\n");
      out.write("\t\t\t<option value=\"3\">curious</option>\n");
      out.write("\t\t\t<option value=\"4\">cute</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent3\" id=\"cent3\"> <br/>\n");
      out.write("\t\t<select name=\"cent4option\" id=\"cent4option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">pathetic</option>\n");
      out.write("\t\t\t<option value=\"2\">huge</option>\n");
      out.write("\t\t\t<option value=\"3\">special</option>\n");
      out.write("\t\t\t<option value=\"4\">crazy</option> \n");
      out.write("\t\t</select>: <input type=\"range\" min=\"1\" max=\"9\" name=\"cent4\" id=\"cent4\"> <br/>\n");
      out.write("\t\t<select name=\"cent5option\" id=\"cent5option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">cool</option> \n");
      out.write("\t\t\t<option value=\"2\">greatest</option> \n");
      out.write("\t\t\t<option value=\"3\">adorable</option>\n");
      out.write("\t\t\t<option value=\"4\">unique</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent5\" id=\"cent5\"> <br/>\n");
      out.write("\t\t<select name=\"cent6option\" id=\"cent6option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">fine</option> \n");
      out.write("\t\t\t<option value=\"2\">goosebumps</option>\n");
      out.write("\t\t\t<option value=\"3\">epic</option>\n");
      out.write("\t\t\t<option value=\"4\">funny</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent6\" id=\"cent6\"> <br/>\n");
      out.write("\t\t<input type=\"button\" value=\"submit\" onclick=\"regAtmos1()\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t<input type=\"button\" value=\"cancel\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t</form>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"tabs-2\">\n");
      out.write("<form method=\"post\" class=\"white fs-m3 fw-200\"\n");
      out.write(" action=\"/SpinUrOwn/regAtmos2.ma\">\n");
if(Atmos=="0"
	||Atmos.split(" ").length!=5){ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz show your prefer Atmos!<br/>\n");
}else{ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz modify your prefer Atmos!<br/>\n");
      out.write("\t\t");
} 
      out.write("\n");
      out.write("\t\t<select name=\"cent1option\" id=\"2cent1option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">gorgeous</option>\n");
      out.write("\t\t\t<option value=\"2\">amazing</option>\n");
      out.write("\t\t\t<option value=\"3\">nice</option>\n");
      out.write("\t\t\t<option value=\"4\">beautiful</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent1\" id=\"2cent1\"> <br/>\n");
      out.write("\t\t<select name=\"cent2option\"id=\"2cent2option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">honest</option>\n");
      out.write("\t\t\t<option value=\"2\">powerful</option>\n");
      out.write("\t\t\t<option value=\"3\">different</option>\n");
      out.write("\t\t\t<option value=\"4\">incredible</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent2\" id=\"2cent2\"> <br/>\n");
      out.write("\t\t<select name=\"cent3option\" id=\"2cent3option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">flawless</option>\n");
      out.write("\t\t\t<option value=\"2\">raw</option>\n");
      out.write("\t\t\t<option value=\"3\">curious</option>\n");
      out.write("\t\t\t<option value=\"4\">cute</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent3\" id=\"2cent3\"> <br/>\n");
      out.write("\t\t<select name=\"cent4option\" id=\"2cent4option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">pathetic</option>\n");
      out.write("\t\t\t<option value=\"2\">huge</option>\n");
      out.write("\t\t\t<option value=\"3\">special</option>\n");
      out.write("\t\t\t<option value=\"4\">crazy</option> \n");
      out.write("\t\t</select>: <input type=\"range\" min=\"1\" max=\"9\" name=\"cent4\" id=\"2cent4\"> <br/>\n");
      out.write("\t\t<select name=\"cent5option\" id=\"2cent5option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">cool</option> \n");
      out.write("\t\t\t<option value=\"2\">greatest</option> \n");
      out.write("\t\t\t<option value=\"3\">adorable</option>\n");
      out.write("\t\t\t<option value=\"4\">unique</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent5\" id=\"2cent5\"> <br/>\n");
      out.write("\t\t<select name=\"cent6option\" id=\"2cent6option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">fine</option> \n");
      out.write("\t\t\t<option value=\"2\">goosebumps</option>\n");
      out.write("\t\t\t<option value=\"3\">epic</option>\n");
      out.write("\t\t\t<option value=\"4\">funny</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent6\" id=\"2cent6\"> <br/>\n");
      out.write("\t\t<input type=\"button\" value=\"submit\" onclick=\"regAtmos2()\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t<input type=\"button\" value=\"cancel\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t</form>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"tabs-3\">\n");
      out.write("<form method=\"post\" class=\"white fs-m3 fw-200\"\n");
      out.write(" action=\"/SpinUrOwn/regAtmos3.ma\">\n");
if(Atmos=="0"
	||Atmos.split(" ").length!=5){ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz show your prefer Atmos!<br/>\n");
}else{ 
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(vo.getNickname());
      out.write(", plz modify your prefer Atmos!<br/>\n");
      out.write("\t\t");
} 
      out.write("\n");
      out.write("\t\t<select name=\"cent1option\" id=\"3cent1option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">gorgeous</option>\n");
      out.write("\t\t\t<option value=\"2\">amazing</option>\n");
      out.write("\t\t\t<option value=\"3\">nice</option>\n");
      out.write("\t\t\t<option value=\"4\">beautiful</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent1\" id=\"3cent1\"> <br/>\n");
      out.write("\t\t<select name=\"cent2option\"id=\"3cent2option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">honest</option>\n");
      out.write("\t\t\t<option value=\"2\">powerful</option>\n");
      out.write("\t\t\t<option value=\"3\">different</option>\n");
      out.write("\t\t\t<option value=\"4\">incredible</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent2\" id=\"3cent2\"> <br/>\n");
      out.write("\t\t<select name=\"cent3option\" id=\"3cent3option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">flawless</option>\n");
      out.write("\t\t\t<option value=\"2\">raw</option>\n");
      out.write("\t\t\t<option value=\"3\">curious</option>\n");
      out.write("\t\t\t<option value=\"4\">cute</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent3\" id=\"3cent3\"> <br/>\n");
      out.write("\t\t<select name=\"cent4option\" id=\"3cent4option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">pathetic</option>\n");
      out.write("\t\t\t<option value=\"2\">huge</option>\n");
      out.write("\t\t\t<option value=\"3\">special</option>\n");
      out.write("\t\t\t<option value=\"4\">crazy</option> \n");
      out.write("\t\t</select>: <input type=\"range\" min=\"1\" max=\"9\" name=\"cent4\" id=\"3cent4\"> <br/>\n");
      out.write("\t\t<select name=\"cent5option\" id=\"3cent5option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">cool</option> \n");
      out.write("\t\t\t<option value=\"2\">greatest</option> \n");
      out.write("\t\t\t<option value=\"3\">adorable</option>\n");
      out.write("\t\t\t<option value=\"4\">unique</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent5\" id=\"3cent5\"> <br/>\n");
      out.write("\t\t<select name=\"cent6option\" id=\"3cent6option\"\n");
      out.write("\t\tclass=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("\t\t\t<option value=\"1\">fine</option> \n");
      out.write("\t\t\t<option value=\"2\">goosebumps</option>\n");
      out.write("\t\t\t<option value=\"3\">epic</option>\n");
      out.write("\t\t\t<option value=\"4\">funny</option>\n");
      out.write("\t\t</select> : <input type=\"range\" min=\"1\" max=\"9\" name=\"cent6\" id=\"3cent6\"> <br/>\n");
      out.write("\t\t<input type=\"button\" value=\"submit\" onclick=\"regAtmos3()\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t<input type=\"button\" value=\"cancel\"\n");
      out.write("\t\tclass=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("\t\tfocus-white fw-300 fs-s3 mr-0 br-l-0\">\n");
      out.write("\t\t</form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\t\t<hr/>\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@15.0.0/dist/smooth-scroll.polyfills.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
