/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-23 16:56:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/Haka4700/SpringWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpinUrOwn/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/Haka4700/SpringWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpinUrOwn/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595550836000L));
    _jspx_dependants.put("jar:file:/Users/Haka4700/SpringWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpinUrOwn/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/shorthandcss@1.1.1/dist/shorthand.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Muli:200,300,400,500,600,700,800,900&display=swap\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css\" />\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\">\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function checkNick() {\n");
      out.write("\t$.ajax({\n");
      out.write("\t    type:\"POST\",\n");
      out.write("\t    url:\"/SpinUrOwn/checkNick.me\",\n");
      out.write("\t    data:{\n");
      out.write("\t           \"Nickname\":$('#Nickname').val()\n");
      out.write("\t    },\n");
      out.write("\t    success:function(data){\t//data : checkSignup에서 넘겨준 결과값\n");
      out.write("           if($.trim(data)==\"YES\"){\n");
      out.write("              if($('#Nickname').val()!=''){ \n");
      out.write("              \talert(\"You can use this Nickname.\");\n");
      out.write("              }\n");
      out.write("          \t}else{\n");
      out.write("              if($('#Nickname').val()!=''){\n");
      out.write("                 alert(\"Already used Nickname.\");\n");
      out.write("                 $('#Nickname').val('');\n");
      out.write("                 $('#Nickname').focus();\n");
      out.write("              }\n");
      out.write("           }\n");
      out.write("\t    }\n");
      out.write("\t}) \n");
      out.write("}\n");
      out.write("function checkID() {\n");
      out.write("\t$.ajax({\n");
      out.write("\t    type:\"POST\",\n");
      out.write("\t    url:\"/SpinUrOwn/checkID.me\",\n");
      out.write("\t    data:{\n");
      out.write("\t           \"ID\":$('#ID').val()\n");
      out.write("\t    },\n");
      out.write("\t    success:function(data){\t//data : checkSignup에서 넘겨준 결과값\n");
      out.write("          if($.trim(data)==\"YES\"){\n");
      out.write("             if($('#ID').val()!=''){ \n");
      out.write("             \talert(\"You can use this ID.\");\n");
      out.write("             }\n");
      out.write("         \t}else{\n");
      out.write("             if($('#ID').val()!=''){\n");
      out.write("                alert(\"Already used ID.\");\n");
      out.write("                $('#ID').val('');\n");
      out.write("                $('#ID').focus();\n");
      out.write("             }\n");
      out.write("          }\n");
      out.write("\t    }\n");
      out.write("\t}) \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-black muli\">\n");
      out.write("<center>\n");
      out.write("<table border=\"1\" width=\"300\" height=\"300\" align= \"center\">\n");
      out.write("\t<span style=\"color: white; font-weight: bold;\">** Write down your account info. **</span>\n");
      out.write("\t<br/><br/>\n");
      out.write("\t<div style=\"text-align:center;\">\n");
      out.write("\t<tr>        \n");
      out.write("\t\t<td>\n");
      out.write("\t\t\t<center>\n");
      out.write("\t<!-- servlet에서 *.do로 url 맵핑, Controller로 이동한 -->\n");
      out.write("\t<form name=\"loginInfo\" action=\"/SpinUrOwn/spmemInsert.me\" method=\"post\"\n");
      out.write("\t onsubmit=\"return checkValue()\">\n");
      out.write("\t <center>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t<input type=\"text\" name=\"Nickname\" id=\"Nickname\" placeholder=\"Nickname\">\n");
      out.write("\t\t<input type=\"button\" value=\"check\" onclick=\"return checkNick()\"><br/>\n");
      out.write("\t\t<input type=\"text\" name=\"ID\" id=\"ID\" placeholder=\"ID\">\n");
      out.write("\t\t<input type=\"button\" value=\"check\" onclick=\"return checkID()\"><br/>\n");
      out.write("\t\t<input type=\"password\" name=\"Password\" placeholder=\"Password\">\n");
      out.write("\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e_mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"Email\"><br/>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input type=\"submit\" value=\"submit\">\n");
      out.write("\t\t<input type=\"reset\" value=\"re-write\">\n");
      out.write("\t\t</div>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                    </center>\n");
      out.write("            </table>\n");
      out.write("\t</form>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
