/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-22 14:59:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import spmem.VO.spmemVO;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("spmem.VO.spmemVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Welcome to SpinUrOwn!</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/shorthandcss@1.1.1/dist/shorthand.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Muli:200,300,400,500,600,700,800,900&display=swap\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css\" />\n");
spmemVO vo = (spmemVO)session.getAttribute("vo");
request.setAttribute("ID", vo.getID());
      out.write('\n');
      out.write('\n');
boolean genzero = vo.getPrefergenre().trim().equals("0"); 
boolean atmoszero = vo.getPreferAtmos().trim().equals("0");
request.setAttribute("ID", vo.getID());
session.setAttribute("ID", vo.getID());
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var count=0;\n");
      out.write("function tofindurmuse(){\n");
      out.write("\tvar sel =0;\n");
      out.write("\tsel = document.getElementById(\"Atmosphere\");\n");
      out.write("\tvar Atmos = \"\";\n");
      out.write("\tfor(i=0; i<sel.options.length; i++) {\n");
      out.write("\t    if(sel.options[i].selected == true) {\n");
      out.write("\t        Atmos = sel.options[i].value;\n");
      out.write("\t        break;\n");
      out.write("\t    }\n");
      out.write("\t}\n");
      out.write("\tvar gen = \"\";\n");
      out.write("\tgen = document.getElementById(\"genreaccept\");\n");
      out.write("\tconst result = $('#view0');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/discovermuse.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tdata:{\n");
      out.write("\t\t\tID : \"0\",\n");
      out.write("\t\t\tPassword : \"0\",\n");
      out.write("\t\t\tcount : count,\n");
      out.write("\t\t\tAtmosphere : Atmos,\n");
      out.write("\t\t\tgenreaccept : gen.value\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\tresult.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("\tcount++;\n");
      out.write("\treturn false;\n");
      out.write("}\n");
      out.write("window.onload = function toall(){\n");
      out.write("\tconst $result1 = $('#view1');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/genreUpdate.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tdata:{\n");
      out.write("\t\t\tID : \"0\",\n");
      out.write("\t\t\tPassword : \"0\"\t\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$result1.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("\tconst $result2 = $('#view2');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/ASLUpdate.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$result2.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("\tconst $result3 = $('#view3');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/AtmosUpdate.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$result3.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("\tconst $result4 = $('#view4');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/rtowrite.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$result4.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("\tconst $result5 = $('#slider-2');\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"/SpinUrOwn/rtoread.ma\",\n");
      out.write("\t\ttype:\"POST\",\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$result5.html(data);\n");
      out.write("\t\t}\n");
      out.write("\t});//ajax end\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-black muli\">\n");
      out.write("\n");
      out.write("<nav class=\"w-100pc flex flex-column md-flex-row md-px-10 py-5 bg-black\">\n");
      out.write("        <div class=\"flex justify-between\">\n");
      out.write("            <a href=\"#\" class=\"flex items-center p-2 mr-4 no-underline\">\n");
      out.write("                <img class=\"max-h-l5 w-auto\" src=\"/SpinUrOwn/img/logo3.png\" \n");
      out.write("                alt=\"SpinUrOwn\" onclick=\"location.href='/SpinUrOwn/main.ma'\"/>\n");
      out.write("            </a>\n");
      out.write("            <a data-toggle=\"toggle-nav\" data-target=\"#nav-items\" href=\"#\"\n");
      out.write("                class=\"flex items-center ml-auto md-hidden indigo-lighter opacity-50 hover-opacity-100 ease-300 p-1 m-3\">\n");
      out.write("                <i data-feather=\"menu\"></i>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        ");
if(genzero){
      out.write("\n");
      out.write("       \t\t<div id=\"nav-items\" class=\"hidden flex sm-w-100pc flex-column md-flex md-flex-row md-justify-end items-center\">\n");
      out.write("            \t<a href=\"#reggenre\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Register your genre</a>\n");
      out.write("            \t<a href='/SpinUrOwn/logout.ma' class=\"button bg-white black fw-600 no-underline mx-5\">logout</a>\n");
      out.write("        \t</div>\n");
      out.write("\t\t");
}else if(atmoszero){
      out.write("\n");
      out.write("\t\t<div id=\"nav-items\" class=\"hidden flex sm-w-100pc flex-column md-flex md-flex-row md-justify-end items-center\">\n");
      out.write("           \t<a href=\"#reggenre\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Register your genre</a>\n");
      out.write("            <a href=\"#regAtmos\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Register your Atmos</a>\n");
      out.write("            <a href='/SpinUrOwn/logout.ma' class=\"button bg-white black fw-600 no-underline mx-5\">logout</a>\n");
      out.write("        </div>\n");
      out.write("\t\t");
}else{
      out.write("\n");
      out.write("        <div id=\"nav-items\" class=\"hidden flex sm-w-100pc flex-column md-flex md-flex-row md-justify-end items-center\">\n");
      out.write("            <a href=\"#FindurMuse\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">FindurMuse</a>\n");
      out.write("            <a href=\"#assong\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Assessment songs</a>\n");
      out.write("            <a href=\"#reggenre\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Register your genre</a>\n");
      out.write("            <a href=\"#regAtmos\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Register your Atmos</a>\n");
      out.write("            <a href=\"#rto\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Recommand song</a>\n");
      out.write("            <a href=\"#myrto\" class=\"fs-s1 mx-3 py-3 indigo no-underline hover-underline\">Check from other</a>\n");
      out.write("            <a href='/SpinUrOwn/logout.ma' class=\"button bg-white black fw-600 no-underline mx-5\">logout</a>\n");
      out.write("        </div>\n");
      out.write("        ");
} 
      out.write("\n");
      out.write("    </nav>\n");
      out.write("    <div id=\"view0\" align=\"center\" class=\"mx-auto py-10\"></div>\n");
      out.write("    ");
if(!genzero && !atmoszero){
      out.write("\n");
      out.write("\t<section id=\"FindurMuse\" class=\"p-10 md-py-10\">\n");
      out.write("            <div class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("                <h4 class=\"white fs-l1 lh-2 md-fs-xl1 md-lh-1 fw-700 \">Find your music rightnow!</h4>\n");
      out.write("\n");
      out.write("                <div class=\"br-8 mt-10 inline-flex\">\n");
      out.write("                <font class=\"white fs-m2 fw-200\">\n");
      out.write("                    <select name=\"Atmosphere\" id=\"Atmosphere\"\n");
      out.write("                    class=\"input-lg half bw-0 fw-200 bg-indigo-lightest-10 white ph-indigo-lightest focus-white opacity-80 fs-s3 py-5 min-w-5vw br-r-0\">\n");
      out.write("                        <option value=\"1\" selected=\"selected\">Atmos1</option>\n");
      out.write("                        ");
if(!vo.getPreferAtmos2().toString().trim().equals("0")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">Atmos2</option>\n");
      out.write("\t\t\t\t\t\t");
}
                        if(!vo.getPreferAtmos3().toString().trim().equals("0")){
      out.write("\n");
      out.write("            \t\t\t<option value=\"3\">Atmos3</option>\n");
      out.write("            \t\t\t");
} 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(vo.getID());
      out.write("\" id=\"ID\" name=\"ID\"/>\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(vo.getPassword());
      out.write("\" id=\"Password\" name=\"Password\"/>\n");
      out.write("                    <input class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700\" id=\"genreaccept\"\n");
      out.write("                     name=\"genreaccept\" type=\"range\" min=\"50\" max=\"500\" maxlength=\"500\"> \n");
      out.write("                     <button value=\"Find my muse\" onclick=\"tofindurmuse()\"\n");
      out.write("                        class=\"button-lg bg-indigo-lightest-20 indigo-lightest \n");
      out.write("                        focus-white fw-300 fs-s3 mr-0 br-l-0\">listen muse</button>\n");
      out.write("                \t</font>\n");
      out.write("                </div>\n");
      out.write("             </div>\n");
      out.write("    </section>\n");
      out.write("    ");
} 
      out.write("\n");
      out.write("    ");
if(!genzero && !atmoszero){
      out.write("\n");
      out.write("    <section class=\"p-10 md-py-10\" id=\"assong\">\n");
      out.write("        <div id=\"view2\"\n");
      out.write("        class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("       \t\t<h1 class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700 \">assong</h1>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    ");
} 
      out.write("\n");
      out.write("    <section class=\"p-10 md-py-10\" id=\"reggenre\">\n");
      out.write("        <div id=\"view1\"\n");
      out.write("        class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("        \t<h1 class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700 \">reggenre</h1>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    ");
if(!genzero){
      out.write("\n");
      out.write("    <section class=\"p-10 md-py-10\" id=\"regAtmos\">\n");
      out.write("        <div id=\"view3\" class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("        \t<h1 class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700 \">regAtmos</h1>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    ");
} 
      out.write("\n");
      out.write("    ");
if(!genzero && !atmoszero){
      out.write("\n");
      out.write("    <section class=\"p-10 md-py-10\" id=\"rto\">\n");
      out.write("        <div id=\"view4\" class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("        \t<h1 class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700 \">rto</h1>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"p-10 md-py-10\" id=\"myrto\">\n");
      out.write("        <div id=\"slider-2\" class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("        \t<h1 class=\"white fs-l3 lh-2 md-fs-xl1 md-lh-1 fw-700 \">myrto</h1>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("     ");
} 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"p-10 md-py-10 md-p-l5 bg-indigo-lightest-10\">\n");
      out.write("<div class=\"w-100pc md-w-70pc mx-auto py-10\">\n");
      out.write("    <div class=\"flex justify-around\">\n");
      out.write("\t\t<div class=\"w-33pc md-px-10 mb-10\">\n");
      out.write("\t\t\t<h5 class=\"white\">About your account</h5>\n");
      out.write("\t\t\t<ul class=\"list-none mt-5 fs-s2\">\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<a href=\"/SpinUrOwn/delaccount.ma\" class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\tDelete account</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t \t\t<a href=\"#\" class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t \t\tChange Password</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<font class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\tDonate to hogu</font>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<font class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\tpaypal : haka4700@gmail.com</font>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
if(vo.getNickname().trim().equals("admin")){
      out.write("\n");
      out.write("\t\t<div class=\"w-33pc md-px-10 mb-10\">\n");
      out.write("\t\t\t<h5 class=\"white\">Console for admin</h5>\n");
      out.write("\t\t\t<ul class=\"list-none mt-5 fs-s2\">\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<a href=\"/SpinUrOwn/showASLall.ma\" \n");
      out.write("\t\t\t\t\tclass=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\tShow ASL all</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t \t\t<a href=\"/SpinUrOwn/showLLall.ma\" \n");
      out.write("\t\t\t \t\tclass=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t \t\tShow LL all</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t \t\t<a href=\"/SpinUrOwn/showRTOall.ma\" \n");
      out.write("\t\t\t \t\tclass=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t \t\tShow RTO all</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
} 
      out.write("\n");
      out.write("\t\t<div class=\"w-33pc md-px-10 mb-10\">\n");
      out.write("\t\t\t<h5 class=\"white\">About your account</h5>\n");
      out.write("\t\t\t<ul class=\"list-none mt-5 fs-s2\">\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\t");
      out.print(genzero);
      out.write("</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t \t\t<a href=\"#\" class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t \t\t");
      out.print(atmoszero );
      out.write("</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<font class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\t");
      out.print(vo.getPreferAtmos() );
      out.write("</font>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"my-3\">\n");
      out.write("\t\t\t\t\t<font class=\"white opacity-70 no-underline hover-underline\">\n");
      out.write("\t\t\t\t\t");
      out.print(vo.getPreferAtmos2() );
      out.write("</font>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</footer>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@15.0.0/dist/smooth-scroll.polyfills.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
